x-typebot-common: &typebot-common
  restart: always
  depends_on:
    typebot-redis:
      condition: service_healthy
    typebot-db:
      condition: service_healthy
  networks:
    - typebot-network
  env_file: .env
  environment:
    REDIS_URL: redis://typebot-redis:6379
    CHOKIDAR_USEPOLLING: "true"
    WATCHPACK_POLLING: "true"

services:
  typebot-db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - typebot-network

  typebot-redis:
    image: redis:alpine
    restart: always
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-data:/data
    networks:
      - typebot-network

  typebot-builder:
    <<: *typebot-common
    build:
      context: .
      target: base
    working_dir: /app
    command: >
      /bin/sh -lc "
      bun install;
      if [ ! -f /app/node_modules/isolated-vm/out/isolated_vm.node ]; then
        rm -rf /app/node_modules/isolated-vm;
        bun install --force;
      fi;
      bunx turbo build --filter=@typebot.io/env;
      ./node_modules/.bin/prisma migrate deploy --schema=packages/prisma/postgresql/schema.prisma;
      bunx turbo dev --filter=builder
      "
    volumes:
      - ./:/app
      - typebot-node-modules:/app/node_modules
    ports:
      - "8090:3000"

  typebot-viewer:
    <<: *typebot-common
    build:
      context: .
      target: base
    working_dir: /app
    command: >
      /bin/sh -lc "
      bun install;
      if [ ! -f /app/node_modules/isolated-vm/out/isolated_vm.node ]; then
        rm -rf /app/node_modules/isolated-vm;
        bun install --force;
      fi;
      bunx turbo build --filter=@typebot.io/env;
      bunx turbo dev --filter=viewer
      "
    volumes:
      - ./:/app
      - typebot-node-modules:/app/node_modules
    ports:
      - "8091:3001"

networks:
  typebot-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
  typebot-node-modules:
